
data = '/data2/Phd_Work1/ICE_Velocity_Process/GAMMA_POT_Output/Mertz_100m/Tidal_IBE_Flexure_Correction/Vx_Vy_V_Weighted_Average/ALL/myear/V_final_myear.tif';
output_dir = '/data2/Phd_Work1/ICE_Velocity_Process/GAMMA_POT_Output/Mertz_100m/Tidal_IBE_Flexure_Correction/Vx_Vy_V_Weighted_Average/ALL/myear/';

result = apply_nlm_tif(data, output_dir, ...
      'H',          50,       ...
      'PatchSize',  7,        ...
      'SearchSize', 21,       ...
      'Colormap',   'turbo',  ...
      'ClimRange',  [0 800],  ...
      'ClimAuto',   false,    ...
      'FigDPI',     300);

data2 = '/data2/Phd_Work1/ICE_Velocity_Process/GAMMA_POT_Output/Mertz_100m/Tidal_IBE_Flexure_Correction/Vx_Vy_V_Weighted_Average/ALL/myear/V_final_myear_NLM_h50.tif';
result2 = apply_fill(data2,output_dir, ...
      'Method',       'region',  ...
      'SmoothFactor', 0.8,        ...
      'Colormap',     'turbo',    ...
      'ClimAuto',     false,      ...
      'ClimRange',    [0 800],    ...
      'FigDPI',       300);