function plot_enhanced_histogram2(data, title_str, range)
    % nexttile(index);
    % 提取有效数据
    valid_data = data(~isnan(data) & ~isinf(data));
    
    if isempty(valid_data)
        text(0.5, 0.5, 'No Valid Data', ...
             'HorizontalAlignment', 'center', ...
             'FontSize', 18, 'Color', 'r', 'FontWeight', 'bold');
        axis off;
        return;
    end
    
    % 设置bins
    n_bins = 120;
    if ~isempty(range)
        edges = linspace(range(1), range(2), n_bins+1);
    else
        edges = n_bins;
    end
    
    % 绘制直方图
    h = histogram(valid_data, edges, ...
                 'FaceColor', [0.2 0.5 0.8], ...
                 'EdgeColor', [0.1 0.3 0.5], ...
                 'EdgeAlpha', 0.3, ...
                 'FaceAlpha', 0.75, ...
                 'LineWidth', 0.5);
    
    hold on;
    
    % 统计量
    mean_val = mean(valid_data);
    median_val = median(valid_data);
    std_val = std(valid_data);
    
    yl = ylim;
    
    % 均值线
    plot([mean_val, mean_val], yl, '--', 'Color', [0.8 0.2 0.2], ...
         'LineWidth', 2.5, 'DisplayName', sprintf('Mean = %.3f', mean_val));
    
    % 中值线
    plot([median_val, median_val], yl, '--', 'Color', [0.2 0.7 0.2], ...
         'LineWidth', 2.5, 'DisplayName', sprintf('Median = %.3f', median_val));
    
    % ±1σ 区域
    x_sigma = [mean_val - std_val, mean_val + std_val];
    patch([x_sigma(1) x_sigma(2) x_sigma(2) x_sigma(1)], ...
          [0 0 yl(2) yl(2)], [0.8 0.2 0.2], ...
          'FaceAlpha', 0.12, ...
          'EdgeColor', 'none', ...
          'DisplayName', sprintf('±1σ = %.3f', std_val));
    
    hold off;
    
    % 设置
    grid on; grid minor;
    xlabel('Value', 'FontSize', 18, 'FontWeight', 'bold');
    ylabel('Frequency', 'FontSize', 18, 'FontWeight', 'bold');
    title(title_str, 'FontSize', 18, 'FontWeight', 'bold', 'Color', [0.15 0.15 0.15]);
    
    % 详细统计文本框
    q25 = prctile(valid_data, 25);
    q75 = prctile(valid_data, 75);
    
    stats_text = sprintf(['N: %d\n' ...
                         'Mean: %.4f\n' ...
                         'Median: %.4f\n' ...
                         'Std: %.4f\n' ...
                         'Min: %.4f\n' ...
                         'Max: %.4f\n' ...
                         'Q25: %.4f\n' ...
                         'Q75: %.4f'], ...
                        length(valid_data), mean_val, median_val, std_val, ...
                        min(valid_data), max(valid_data), q25, q75);
    
    text(0.98, 0.98, stats_text, ...
         'Units', 'normalized', ...
         'VerticalAlignment', 'top', ...
         'HorizontalAlignment', 'right', ...
         'FontSize', 18, ...
         'FontName', 'Courier New', ...
         'BackgroundColor', [1 1 1 0.9], ...
         'EdgeColor', [0.3 0.3 0.3], ...
         'LineWidth', 1, ...
         'Margin', 5);
    
    % 图例
    legend('Location', 'northwest', 'FontSize', 18, 'Box', 'on');
    
    % 美化
    box on;
    set(gca, 'FontSize', 18, 'LineWidth', 1);
    
    % 设置x轴范围
    if ~isempty(range)
        xlim(range);
    end
end