clc;clear
range = '/data2/Phd_Work1/ICE_Velocity_Process/GAMMA_POT_Output/Cook_120m/Remove_outliers_Correction/range';
azimuth = '/data2/Phd_Work1/ICE_Velocity_Process/GAMMA_POT_Output/Cook_120m/Remove_outliers_Correction//azimuth';
geomotry = '/data2/Phd_Work1/ICE_Velocity_Process/GAMMA_POT_Output/Cook_120m/Remove_outliers_Correction//geometry';
outdir = '/data2/Phd_Work1/ICE_Velocity_Process/GAMMA_POT_Output/Cook_120m/Remove_outliers_Correction//velocity';

gamma_pot_to_velocity(range, azimuth, geomotry, ...
    'range_suffix', 'range-nmt_filtered', ...
    'azi_suffix', 'azi-nmt_filtered', ...
    'lv_phi_fallback', '20231031.lv_phi.tif', ...
    'output_dir', outdir )
